### ISSUE TITLE
Remove pumps that don't exist

### ISSUE THREAD

**Issue by miamijerry** [tagyoureit/nodejs-poolController#220]
How do I remove the pumps showing in attached pictures?

There are no pumps
![Pumps showing](https://user-images.githubusercontent.com/8471168/94454478-e6d31680-017f-11eb-8acf-8d0b89cf31ae.JPG)

**Comment by tagyoureit** [comment]
Have you pulled `next` with the updated OCP configuration?  This issue should resolve itself once the OCP is configured properly.

**Comment by miamijerry** [comment]
This multiple pump showing issue is on a Aux 8 P/N 520657 motherboard.

**Comment by miamijerry** [comment]
Earlier this RPI was connected to the 522523 Easytouch Lite board on work bench.

Then I moved the RPI outside and connected to Easytouch Aux 8

The issue with the pumps has not resolved itself...

**Comment by miamijerry** [comment]
Resolved by replacing SD card image from before connection with 522523 Easytouch Lite PL4 board
