### ISSUE TITLE
IntelliCenter / MasterTemp RS485 replay capture

### ISSUE THREAD

**Issue by bad350trk** [tagyoureit/nodejs-poolController#368]
MasterTemp w/ RS-485 comms connected to Intellicenter.  Sending in a capture and information to see the conversation between MT and IC.

Here's the replay.
[replay 1916_22NOV2021.zip](https://github.com/tagyoureit/nodejs-poolController/files/7585539/replay.1916_22NOV2021.zip)

And here's the description of what I did.
[Heater comms test 1.docx](https://github.com/tagyoureit/nodejs-poolController/files/7585549/Heater.comms.test.1.docx)

Thanks!

--Jeff

**Comment by rstrouse** [comment]
So I have done a quick breeze through of the messages and have witnessed a couple of things.

First this is similar to the UltraTemp protocol.  There are only 2 messages involved where the OCP sends a request to the heater and the heater responds with its status.

The first message is a message sent from the OCP to the heater with a 12 byte payload.  It is a request message that contains a command to the heater and the setpoints.  These are all contained within the first 3 bytes.  The message below is one where it is calling for heat to the spa setpoint (96).  I assume the other setpoint (pool) is set to 78.  
`[255, 0, 255][165, 0, 112, 16, 112, 12][2, 78, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0][2, 81]`

The message is broken down like this.
`[255, 0, 255]` = Message preamble
`[165, 0, 112, 16, 112, 12]` = The first 2 bytes are the controller and protocol values followed by the destination  (112:Heater at address 1) and the source (16:OCP).  The next byte is the action byte (112:Request status) finally followed by the length of the payload in the next section.

So here is what we know of the payload starting with the first byte index.
`[2, 78, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0]`
2 = Heat to the spa setpoint 96.
78 = Pool setpoint
96 = Spa setpoint

We know nothing about the remaining bytes.  These could be nothing or they could mean something.  The punchline is that they never change.

So that was the command message.  The response message is a larger message that has a payload 22 bytes long.  Here is what the changes look like for this message in the capture you sent.
![image](https://user-images.githubusercontent.com/47839015/143074441-b97bf680-dbbf-499e-843c-1eed84692b24.png)

Btw if you want to play around with the messages you have access to this tool as well.  The basic wiki instructions are here.  The wiki needs a couple of updates related to the filter icon on the header but essentially it will filter messages out of your current list by checking the box next to the message signature.
https://github.com/rstrouse/nodejs-poolController-dashPanel/wiki/Message-Manager

**Comment by rstrouse** [comment]
I have also determined that the IntelliCenter status message is changed when the heater is a MasterTemp on RS485.  This is consistent with the way UltraTemp works.  I thought it was weird when I saw it with UltraTemp but it explains why the mode and status indicators in dashPanel are showing off.

**Comment by rstrouse** [comment]
Also what heat mode was the pool in when you were capturing?

**Comment by rstrouse** [comment]
I have added the code for MasterTemp so if you pull njsPC it should now show the proper selections in dashPanel as well as.  We may have some tweaks to do there based upon our collaboration.

**Comment by bad350trk** [comment]
Sorry, I don't understand your question about heat mode.  If you mean Pool or Spa, it was in Spa mode.

**Comment by bad350trk** [comment]
I will try a pull later this evening and see what shows up.

**Comment by rstrouse** [comment]
The heat mode will be either Off or (MasterTemp or Heater) depending on how Pentair labeled this.  I am guessing that it was Off.

![image](https://user-images.githubusercontent.com/47839015/143144418-994e82c4-df7d-469a-a1a8-bca8ff898fec.png)

**Comment by bad350trk** [comment]
Understand now.   Yes, the pool was set to off.

**Comment by bad350trk** [comment]
Tried a pull in njsPC.  I get the following error:

error: cannot open .git/FETCH_HEAD: Permission denied

**Comment by rstrouse** [comment]
Are you in the nodejs-poolController directory.
`cd ~/nodejs-poolController`
`git pull`

If you are then the issue is that the user you are logged in as does not have write access to the directory.  You can use
`sudo git pull` but I would check to see who the owner of the nodejs-poolController directory is.

I hate linux permissions.

**Comment by rstrouse** [comment]
Run the following commands to set the ownership.
`cd ~/nodejs-poolController`
`sudo chown -R $(whoami) .git/`

**Comment by bad350trk** [comment]
Sweet!  That worked!  Set ownership and then the pull worked.

**Comment by bad350trk** [comment]
I have not had time to do a thorough run through to try and capture the errors on the RS-485 bus.  But I have noticed a few things while using the heater this weekend.

1 - There is no way for me to turn on the heater from either pool or spa selection. When I select the pop-up to turn on the heater, this is all I see...
![Pool Heater Off](https://user-images.githubusercontent.com/25586223/143774027-8a539d40-9863-41ec-a2cb-e4cdee28d8bb.png)
When I click on the OFF radio button in this state, nothing happens.

2 - I turned on the heater using the IC web client.  This is how njsPC shows the heater.  I was expecting the Heat Mode to show - MasterTemp, and the Heater Status to show - ON.
![Pool Heater Running](https://user-images.githubusercontent.com/25586223/143774098-81278539-a1a7-47d9-9f23-234842ff0134.png)

With the heater running, I can turn it off using the pop-up OFF radio button.  That function works just fine.
![Pool Heater turn off](https://user-images.githubusercontent.com/25586223/143774148-56e3fb60-e941-492d-a6b3-62d06ca061d1.png)

3 - The heater type is inverted between the IC and njsPC.  If the IC has the heater type configured as MasterTemp, it shows up as Max E Therm in njsPC (see screen shot below).
![Heater Type](https://user-images.githubusercontent.com/25586223/143774245-9230f78b-ff3c-4d1f-9906-1f848e580f52.png)

To confirm this, I deleted the heater in njsPC and added a new heater and selected MasterTemp from the type drop down.  When I went to the IC web client, the heater shows up as Max E Therm.

I did not grab any captures for this, I certainly can if necessary, if the previous one does not have sufficient info.

Thanks,

--Jeff

**Comment by rstrouse** [comment]
Please pull njsPC.  I fixed the differential between Max-E-Therm and MasterTemp several days ago.  This was inverted but it should not be inverted anymore.  This will also make it so that the heat modes and status are incorrect.  Then after you do that go to the hamburger menu and navigate to the System tab and hit Reload Config.  This will ask IntelliCenter to send its configuration again.

**Comment by bad350trk** [comment]
Hmmm... Doesn't seem to change anything.  Just did a git pull on both njsPC and dashpanel, then reloaded the configuration from IC.  Still seeing the same issues as mentioned above.

**Comment by rstrouse** [comment]
I will need a replay when it is reloading the config.  So select the Capture Replay then go to the Reload Config.

**Comment by bad350trk** [comment]
I think I got it.  I selected the capture configuration reload option and then started the capture.  Once the system showed Ready again, I cancelled the capture.

[replay 28NOV2021.zip](https://github.com/tagyoureit/nodejs-poolController/files/7614312/replay.28NOV2021.zip)

--Jeff

**Comment by rstrouse** [comment]
Pull njsPC then reload the config from the System Tab.  I switched the identifiers around.

**Comment by bad350trk** [comment]
Alright.  Did that.  That corrected the MasterTemp / Max E Therm on the heater settings
![MasterTemp MaxETherm correct](https://user-images.githubusercontent.com/25586223/143789523-bfc987b5-a9e0-46bf-9155-a16ae4412ff6.png)

Here's the screen before I turned the heater on.
![MasterTemp Ready to turn on](https://user-images.githubusercontent.com/25586223/143789589-3050e83d-2612-4fdf-a8f0-c1c2f73540c1.png)

The bottom radio button, I am assuming is supposed to be the ON button.  I attempted to turn on the heater using that button, but nothing happened.  After turning on the heater via the IC, here is what I see...
![MasterTemp on](https://user-images.githubusercontent.com/25586223/143789730-3c579409-a167-4906-a6c2-17701f2550df.png)

Here is the most recent capture loading the configuration after the last pull, in case you need that.

[replay 28NOV2021 (2).zip](https://github.com/tagyoureit/nodejs-poolController/files/7614580/replay.28NOV2021.2.zip)

Let me know if there is anything else you need me to do/look at.

Thanks so much for looking into this!  

--Jeff

**Comment by rstrouse** [comment]
I need a capture of you changing the heat mode from off to on then back to off again.  I do not need the config.

**Comment by bad350trk** [comment]
Started capture, turned heater on, about 45 seconds later turned it off, about 45 seconds turned it on, about 45 seconds later turned it off.  Stopped capture.

[replay Heater off_on.zip](https://github.com/tagyoureit/nodejs-poolController/files/7614677/replay.Heater.off_on.zip)

--Jeff

**Comment by rstrouse** [comment]
Pull njsPC.  I added the sequences for the heat modes related to MasterTemp.

**Comment by bad350trk** [comment]
Very nice!  That's it!  

Able to turn on/off the heater now, and heat mode shows up as MasterTemp.
![Spa heater selection](https://user-images.githubusercontent.com/25586223/143964244-a3eb5bb4-356b-4dfc-aff4-ebbe57de7eff.png)

Still planning on running through a sequence where I cause alarm trips.  Hopefully this upcoming weekend.

Thanks!

--Jeff

**Comment by rstrouse** [comment]
Is the heater currently running?  I would have expected to see the flames when it is on.
![image](https://user-images.githubusercontent.com/47839015/143972581-f1a2216a-dddb-4cee-be8c-e52fd3e3e681.png)

**Comment by rstrouse** [comment]
Pull dashPanel and hard refresh your browser.  The flames should appear for MasterTemp now when it is heating.

**Comment by bad350trk** [comment]
Oh.  Didn't realize there was supposed to be a flame symbol.  Ok.  Did a pull on dashPanel.  Do not know what a hard refresh means on my browser, but completely closed out and reopened, and don't see the flame.  So restarted the computer and reopened and still don't see the flame.  Still looks like this.

![Heater current](https://user-images.githubusercontent.com/25586223/143979076-8bd5f854-5d9c-4093-86e7-38f48f05a9e8.png)

--Jeff

**Comment by rstrouse** [comment]
Ctrl + F5 on windows and something else on a Mac.  If this is an iPad you have to clear the browser cache.  But be careful it isn't very smart so you have to go in and delete the data for the individual web site.  Apple can be so stupid sometimes.

**Comment by bad350trk** [comment]
Windows machine.  CTL + F5 didn't seem to have any effect.  Had to go into settings and clear the browser cache.  Showing up now!

![Pool w_flame](https://user-images.githubusercontent.com/25586223/143980636-bf8d5e6b-99b3-4464-a2ed-ccc6bf1d6573.png)

![Heat w_flame](https://user-images.githubusercontent.com/25586223/143980642-8985b659-2427-477e-b1b9-203d3526c4fb.png)

Thanks!

--Jeff

**Comment by rstrouse** [comment]
I am going to close this for now.  If you have any more issues please submit another issue.
